### ISSUE TITLE
Set minimum number of cores to 1

### ISSUE THREAD

**Issue by ItsKarlito** [TheLastBilly/LaboratoriesCOEN346#13]
I'm able to pass an input file with number of cores set to 0.

![image](https://user-images.githubusercontent.com/52050441/113493694-cded4a00-94af-11eb-887b-dce7d973b288.png)

**Comment by yhaydar** [comment]
Fix pushed in "develop" branch. Working for me. Need a second person to check

**Comment by ItsKarlito** [comment]
Works, thank you.
