### ISSUE TITLE
Mismatch of number of processes.

### ISSUE THREAD

**Issue by ItsKarlito** [TheLastBilly/LaboratoriesCOEN346#14]
The program should detect the mismatch between number of processes variable and the actual number of process lines in an input file. The parser should throw an error to the user.

![image](https://user-images.githubusercontent.com/52050441/113493760-58ce4480-94b0-11eb-932c-24f45d70f8ba.png)

**Comment by yhaydar** [comment]
Please verify in develop

**Comment by ItsKarlito** [comment]
Works, thank you.
